enableGlobalCache: true

nodeLinker: node-modules

plugins:
    - path: ./.yarn/plugins/postinstallDev.cjs
    - checksum: f8ce3a541a57481f6213647cfe7ac8555d87cb1fc23a73a102e64e12be07f603826d822f4d0285333400f0f15baed92510c33dcce75dde2953b2811e36efa012
      path: .yarn/plugins/@yarnpkg/plugin-git-hooks.cjs
      spec: "https://raw.githubusercontent.com/trufflehq/yarn-plugin-git-hooks/main/bundles/%40yarnpkg/plugin-git-hooks.js"

gitHooksPath: .github/hooks
