import { describe, expect, test } from 'vitest';

import { compareToHeader, readHeader, readHeaders } from '../../../../src/lib/schema-to-ts/check.js';
import { emit, header, type EmitOptions } from '../../../../src/lib/schema-to-ts/emit.js';
import { IR_VERSION, type IRNode, type IRRoot } from '../../../../src/lib/schema-to-ts/ir.js';
import { jsonSchemaToIR } from '../../../../src/lib/schema-to-ts/json-schema-to-ir.js';

const OPTS: EmitOptions = { types: [{ name: 'Input', variant: 'received' }] };

const SCHEMA = {
	type: 'object',
	properties: { a: { type: 'string' }, b: { type: 'integer', default: 1 } },
	required: ['a'],
};

function irOf(schema: unknown): IRRoot {
	return jsonSchemaToIR(schema).ir;
}

const wrap = (node: IRNode): IRRoot => ({ irVersion: IR_VERSION, root: node });

describe('readHeaders', () => {
	test('round-trips whatever the emitter writes', () => {
		const parsed = readHeader(header('abcdef0123456789'));
		expect(parsed).toEqual({ version: IR_VERSION, hash: 'abcdef0123456789', index: 0 });
	});

	test('finds the header below a CLI-prepended banner', () => {
		const source = [
			'/* eslint-disable */',
			'// generated by our CLI',
			header('aaaa'),
			'',
			'export type T = string;',
		].join('\n');
		expect(readHeader(source)?.hash).toBe('aaaa');
	});

	test('tolerates CRLF line endings', () => {
		const source = [header('bbbb'), '', 'export type T = string;'].join('\r\n');
		expect(readHeader(source)?.hash).toBe('bbbb');
	});

	test('is null when there is no header', () => {
		expect(readHeader('export type T = string;\n')).toBeNull();
		expect(readHeaders('export type T = string;\n')).toEqual([]);
	});

	test('does not match a near-miss', () => {
		expect(readHeader('// @generated schema-ts v1-NOTHEX — do not edit\n')).toBeNull();
		expect(readHeader('// @generated schema-ts v1-abcd - do not edit\n')).toBeNull();
		expect(readHeader('  // @generated schema-ts v1-abcd — do not edit\n')).toBeNull();
	});

	test('reads a future version rather than failing to recognise the line', () => {
		expect(readHeader('// @generated schema-ts v99-abcd — do not edit\n')).toEqual({
			version: 99,
			hash: 'abcd',
			index: 0,
		});
	});

	test('reports every header, and readHeader refuses to guess between them', () => {
		const source = [header('aaaa'), 'export type T = string;', header('bbbb')].join('\n');
		expect(readHeaders(source).map((h) => h.hash)).toEqual(['aaaa', 'bbbb']);
		expect(readHeader(source)).toBeNull();
	});

	test('is not stateful across calls', () => {
		const source = header('cccc');
		expect(readHeader(source)?.hash).toBe('cccc');
		expect(readHeader(source)?.hash).toBe('cccc');
	});
});

describe('compareToHeader', () => {
	test('a freshly emitted file matches', () => {
		const ir = irOf(SCHEMA);
		const result = compareToHeader(emit(ir, OPTS), ir, OPTS);
		expect(result.stale).toBe(false);
		expect(result.reason).toBe('match');
		expect(result.found).toBe(result.expected);
	});

	test('a type-relevant schema edit is stale', () => {
		const source = emit(irOf(SCHEMA), OPTS);
		const edited = irOf({ ...SCHEMA, required: ['a', 'b'] });
		const result = compareToHeader(source, edited, OPTS);
		expect(result).toMatchObject({ stale: true, reason: 'hash-mismatch' });
		expect(result.found).not.toBe(result.expected);
	});

	test('a cosmetic schema edit is not', () => {
		const source = emit(irOf(SCHEMA), OPTS);
		const cosmetic = irOf({
			...SCHEMA,
			title: 'A title',
			properties: { a: { type: 'string', editor: 'textarea', prefill: 'x' }, b: { type: 'number', default: 1 } },
		});
		expect(compareToHeader(source, cosmetic, OPTS).reason).toBe('match');
	});

	test('renaming the declaration or switching the variant is stale', () => {
		const ir = irOf(SCHEMA);
		const source = emit(ir, OPTS);
		expect(compareToHeader(source, ir, { types: [{ name: 'Renamed', variant: 'received' }] }).reason).toBe(
			'hash-mismatch',
		);
		expect(compareToHeader(source, ir, { types: [{ name: 'Input', variant: 'supplied' }] }).reason).toBe(
			'hash-mismatch',
		);
	});

	test('a hand-written file is not ours to overwrite', () => {
		const result = compareToHeader('export type Input = { a: string };\n', irOf(SCHEMA), OPTS);
		expect(result).toMatchObject({ stale: true, reason: 'missing-header', found: null, foundVersion: null });
	});

	test('two headers — a botched merge — is its own failure', () => {
		const ir = irOf(SCHEMA);
		const source = emit(ir, OPTS) + emit(ir, OPTS);
		expect(compareToHeader(source, ir, OPTS)).toMatchObject({
			stale: true,
			reason: 'duplicate-header',
			found: null,
		});
	});

	test('version mismatch outranks the hash, since hashes are not comparable across versions', () => {
		const ir = irOf(SCHEMA);
		const fromTheFuture = emit(ir, OPTS).replace(`v${IR_VERSION}-`, 'v99-');
		const result = compareToHeader(fromTheFuture, ir, OPTS);
		// Same hash, different version — still reported as a version mismatch, not a match.
		expect(result).toMatchObject({ stale: true, reason: 'version-mismatch', foundVersion: 99 });
		expect(result.found).toBe(result.expected);
		expect(result.expectedVersion).toBe(IR_VERSION);
	});

	test('an unknown root is checkable like anything else', () => {
		const ir = wrap({ kind: 'unknown' });
		expect(compareToHeader(emit(ir, OPTS), ir, OPTS).reason).toBe('match');
		// The softer root is a different file, so it must not pass as the same one.
		expect(compareToHeader(emit(ir, OPTS), ir, { ...OPTS, unknownRoot: 'record' }).reason).toBe('hash-mismatch');
	});
});

describe('formatting immunity', () => {
	/** The whole reason the fingerprint exists: Prettier must not be able to fake drift. */
	const reformat = (source: string): string =>
		source
			.replace(/^ {4}/gm, '  ') // re-indent
			.replace(/;$/gm, ',') // trailing commas instead of semicolons
			.replace(/\n\n/g, '\n\n\n') // extra blank lines
			.replace(/^export type/m, '\nexport  type'); // stray whitespace

	test('survives a reformatted body', () => {
		const ir = irOf(SCHEMA);
		const result = compareToHeader(reformat(emit(ir, OPTS)), ir, OPTS);
		expect(result.reason).toBe('match');
		expect(result.stale).toBe(false);
	});

	test('survives CRLF normalisation and a trailing-newline change', () => {
		const ir = irOf(SCHEMA);
		const crlf = emit(ir, OPTS).replace(/\n/g, '\r\n').trimEnd();
		expect(compareToHeader(crlf, ir, OPTS).reason).toBe('match');
	});

	test('but a real schema change still lands', () => {
		const source = reformat(emit(irOf(SCHEMA), OPTS));
		expect(compareToHeader(source, irOf({ ...SCHEMA, properties: { a: { type: 'number' } } }), OPTS).reason).toBe(
			'hash-mismatch',
		);
	});
});
