import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

import { compile } from 'json-schema-to-typescript';

import { ApifyCommand } from '../../lib/command-framework/apify-command.js';
import { Args } from '../../lib/command-framework/args.js';
import { Flags } from '../../lib/command-framework/flags.js';
import { success } from '../../lib/outputs.js';

export const BANNER_COMMENT = `
/* eslint-disable */
/* biome-ignore-all lint */
/* biome-ignore-all format */
/* prettier-ignore-start */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run apify actor generate-types to regenerate this file.
 */
`;

export class ActorGenerateTypesCommand extends ApifyCommand<typeof ActorGenerateTypesCommand> {
	static override name = 'generate-types' as const;

	static override description = 'Generate TypeScript types from a JSON schema file.';

	static override flags = {
		output: Flags.string({
			char: 'o',
			description: 'Directory where the generated files should be outputted.',
			required: false,
			default: './.generated/actor/',
		}),
		strict: Flags.boolean({
			char: 's',
			description: 'Whether generated interfaces should be strict (no index signature [key: string]: unknown).',
			required: false,
			default: true,
		}),
	};

	static override args = {
		path: Args.string({
			required: true,
			description: 'Path to the JSON schema file.',
		}),
	};

	async run() {
		const inputPath = this.args.path;
		const absolutePath = path.resolve(process.cwd(), inputPath);

		const schemaContent = await readFile(absolutePath, 'utf-8');
		const schema = JSON.parse(schemaContent);

		const name = path.basename(inputPath, path.extname(inputPath));

		const result = await compile(schema, name, {
			bannerComment: BANNER_COMMENT,
			maxItems: -1,
			unknownAny: true,
			format: true,
			additionalProperties: !this.flags.strict,
			$refOptions: { resolve: { external: false, file: false, http: false } },
		});

		const outputDir = path.resolve(process.cwd(), this.flags.output);
		await mkdir(outputDir, { recursive: true });

		const outputFile = path.join(outputDir, `${name}.ts`);
		await writeFile(outputFile, result, 'utf-8');

		success({ message: `Generated types written to ${outputFile}` });
	}
}
