import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

import type { JSONSchema4 } from 'json-schema';
import { compile } from 'json-schema-to-typescript';

import { ApifyCommand } from '../../lib/command-framework/apify-command.js';
import { Args } from '../../lib/command-framework/args.js';
import { Flags } from '../../lib/command-framework/flags.js';
import { LOCAL_CONFIG_PATH } from '../../lib/consts.js';
import { readAndValidateInputSchema } from '../../lib/input_schema.js';
import { success } from '../../lib/outputs.js';

export const BANNER_COMMENT = `
/* eslint-disable */
/* biome-ignore-all lint */
/* biome-ignore-all format */
/* prettier-ignore-start */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run apify actor generate-types to regenerate this file.
 */
`;

export class ActorGenerateTypesCommand extends ApifyCommand<typeof ActorGenerateTypesCommand> {
	static override name = 'generate-types' as const;

	static override description = `Generate TypeScript types from an Actor input schema.

Reads the input schema from one of these locations (in priority order):
  1. Object in '${LOCAL_CONFIG_PATH}' under "input" key
  2. JSON file path in '${LOCAL_CONFIG_PATH}' "input" key
  3. .actor/INPUT_SCHEMA.json
  4. INPUT_SCHEMA.json

Optionally specify custom schema path to use.`;

	static override flags = {
		output: Flags.string({
			char: 'o',
			description: 'Directory where the generated files should be outputted.',
			required: false,
			default: 'src/.generated/actor/',
		}),
		strict: Flags.boolean({
			char: 's',
			description: 'Whether generated interfaces should be strict (no index signature [key: string]: unknown).',
			required: false,
			default: true,
		}),
	};

	static override args = {
		path: Args.string({
			required: false,
			description: 'Optional path to the input schema file. If not provided, searches default locations.',
		}),
	};

	async run() {
		const { inputSchema, inputSchemaPath } = await readAndValidateInputSchema({
			forcePath: this.args.path,
			cwd: process.cwd(),
			action: 'Generating types from',
		});

		const name = inputSchemaPath ? path.basename(inputSchemaPath, path.extname(inputSchemaPath)) : 'input';

		const result = await compile(inputSchema as JSONSchema4, name, {
			bannerComment: BANNER_COMMENT,
			maxItems: -1,
			unknownAny: true,
			format: true,
			additionalProperties: !this.flags.strict,
			$refOptions: { resolve: { external: false, file: false, http: false } },
		});

		const outputDir = path.resolve(process.cwd(), this.flags.output);
		await mkdir(outputDir, { recursive: true });

		const outputFile = path.join(outputDir, `${name}.ts`);
		await writeFile(outputFile, result, 'utf-8');

		success({ message: `Generated types written to ${outputFile}` });
	}
}
