name: Cucumber E2E tests

on:
    workflow_dispatch:
    push:
        paths:
            - "features/**"
    # risky... but we trust our developers :finger_crossed:
    # pull_request:
    #   paths:
    #     - "features/**"

jobs:
    make_salad:
        name: Cucumber tests
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-2025]
                # We only test LTS for now
                node-version: [22]

        runs-on: ${{ matrix.os }}

        steps:
            - name: Mask secrets
              run: |
                  echo "::add-mask::${{ secrets.APIFY_TEST_USER_API_TOKEN }}"

            - uses: actions/checkout@v5

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Enable corepack
              run: |
                  corepack enable
                  corepack prepare yarn@stable --activate

            - name: Activate cache for yarn
              uses: actions/setup-node@v4
              with:
                  cache: yarn

            - name: Install Dependencies
              run: yarn

            - name: Run Cucumber tests
              env:
                  APIFY_CLI_DISABLE_TELEMETRY: 1
                  TEST_USER_TOKEN: ${{ secrets.APIFY_TEST_USER_API_TOKEN }}
              run: yarn test:cucumber
