name: docs

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build:
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}

        environment:
            name: github-pages

        permissions:
            contents: write
            pages: write
            id-token: write

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5
              with:
                  token: ${{ secrets.APIFY_SERVICE_ACCOUNT_GITHUB_TOKEN }}

            - name: Use Node.js 22
              uses: actions/setup-node@v6
              with:
                  node-version: 22
                  package-manager-cache: false

            - name: Enable corepack
              run: |
                  corepack enable
                  corepack prepare yarn@stable --activate

            - name: Activate cache for yarn
              uses: actions/setup-node@v6
              with:
                  cache: yarn

            - name: Build docs
              run: |
                  # install project deps
                  yarn
                  # update next docs reference
                  yarn update-docs
                  # go to website dir
                  cd website
                  # install website deps
                  yarn
                  # install the latest theme version
                  yarn add @apify/docs-theme@latest
                  # build the docs
                  yarn build
              env:
                  SMARTLOOK_PROJECT_KEY: ${{ secrets.SMARTLOOK_DOCS_PROJECT_KEY }}
                  GIT_USER: "apify-service-account:${{ secrets.APIFY_SERVICE_ACCOUNT_GITHUB_TOKEN }}"
                  GH_TOKEN: ${{ secrets.APIFY_SERVICE_ACCOUNT_GITHUB_TOKEN }}
                  APIFY_SIGNING_TOKEN: ${{ secrets.APIFY_SIGNING_TOKEN }}

            - name: Commit the updated package(-lock).json
              uses: stefanzweifel/git-auto-commit-action@v6
              with:
                  commit_message: "chore: Automatic theme updating workflow [skip ci]"
                  file_pattern: "website/package*.json website/yarn.lock"
                  commit_user_name: Apify Bot
                  commit_user_email: my-github-actions-bot@example.org
                  commit_author: Apify Bot <apify@apify.com>

            - name: Set up GitHub Pages
              uses: actions/configure-pages@v5

            - name: Upload GitHub Pages artifact
              uses: actions/upload-pages-artifact@v4
              with:
                  path: ./website/build

            - name: Deploy artifact to GitHub Pages
              uses: actions/deploy-pages@v4

            - name: Invalidate CloudFront cache
              run: gh workflow run invalidate.yaml --repo apify/apify-docs-private
              env:
                  GITHUB_TOKEN: ${{ secrets.APIFY_SERVICE_ACCOUNT_GITHUB_TOKEN }}
